# Generated by Django 2.2.3 on 2019-08-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/')),
                ('imgdetail', models.ImageField(upload_to='photo/')),
                ('titre', models.CharField(max_length=30)),
                ('prix', models.IntegerField()),
                ('information', models.TextField(null=True)),
                ('telephone', models.IntegerField(default=0)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monappartement.Categorie')),
            ],
        ),
    ]
