# Generated by Django 2.2.3 on 2019-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappartement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='information',
            new_name='infochambre',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='imgdetail',
        ),
        migrations.AddField(
            model_name='produit',
            name='imgchambre',
            field=models.ImageField(default='DEFAULT', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='imgcuisine',
            field=models.ImageField(default='DEFAULT', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='imgdouche',
            field=models.ImageField(default='DEFAULT', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='infocuisine',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='infodouche',
            field=models.TextField(null=True),
        ),
    ]
